---

#- group: name={{ weblate_user }} state=present

- name: Create weblate user and home directory
  user: name={{ weblate_user }} home={{ weblate_user_home }} group=root

- name: Install epel-release and mysql repos
  yum: name={{ item }} state=installed
  with_items:
    - epel-release
    - http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm

- name: Install essential packages
  yum: name={{ item }} state=installed
  with_items:
    - python-pip
    - python-virtualenv
    - mysql-server
    - python-devel
    - git
    - wget
    - gcc
    - libxml2-devel
    - libxslt-devel
    - zlib-devel
    - libjpeg-turbo-devel
    - libtiff-devel
    - freetype-devel
    - lcms2-devel
    - libwebp-devel
    - tcl-devel
    - openjpeg-devel
    - MySQL-python
    - mysql-devel


- name: Start up mysql server
  service: name=mysqld state=started enabled=yes

- git: repo=https://github.com/nijel/weblate.git
       dest={{ weblate_user_home }}/weblate
       version={{ weblate_version }}
  become: yes
  become_user: "{{ weblate_user }}"

- name: Create virtualenv
  pip: requirements={{ weblate_user_home }}/weblate/requirements.txt virtualenv={{ weblate_user_home }}/venv
  become: yes
  become_user: "{{ weblate_user }}"

- template: src=bashrc.j2 dest={{ weblate_user_home }}/.bashrc
  become: yes
  become_user: "{{ weblate_user }}"

- template: src=settings.py.j2 dest={{ weblate_user_home }}/weblate/weblate/settings.py
  become: yes
  become_user: "{{ weblate_user }}"

- include: database.yml
  when: generate_assets == "true"

- include: nginx.yml

- name: Check if app is running
  shell: curl --silent {{ ansible_ssh_host }} | grep weblate
  register: curlout
  failed_when: curlout.stdout == ""
