---

- name: Install nginx and related packages
  yum: name={{ item }} state=installed
  with_items:
    - nginx

- name: Install uwsgi to venv
  pip: name=uwsgi virtualenv={{ weblate_user_home }}/venv
  become: yes
  become_user: "{{ weblate_user }}"

- template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf

- template: src=templates/weblate.conf.j2 dest=/etc/nginx/conf.d/weblate.conf

- template: src=templates/weblate.uwsgi.ini.j2 dest={{ weblate_user_home }}/weblate/weblate.uwsgi.ini
  become: yes
  become_user: "{{ weblate_user }}"

- name: Start app
  shell: ./manage.py runserver 127.0.0.1:8008 &
  args:
    chdir: "{{ weblate_user_home }}/weblate"
  become: yes
  become_user: "{{ weblate_user }}"

- name: Start up nginx
  service: name=nginx state=started enabled=yes

- name: WARNING! DISABLING SELINUX!
  shell: setenforce 0
